ifndef::imagesdir[:imagesdir: ../images]

[[section-introduction-and-goals]]
== Introduction and Goals

ifdef::arc42help[]
[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. 
These include

* underlying business goals, 
* essential features, 
* essential functional requirements, 
* quality goals for the architecture and
* relevant stakeholders and their expectations
**** 
endif::arc42help[]

_project_name_ is an administrative system for a landlord that rents houses.
It's main goals are to facilitate the landlord to administrate the followings:
* rental objects
* tennants
* service charge billings
The project should also give the tennants a portal to check their daily consumptions of heating energy and water.
...

This is a project of _students_names_

=== Requirements Overview

.Contents
The main purpose of _project_name_ is keeping track of all the rental objects, tennants informations, billings, consumptions and sensor management so that the landlord has all the informations updated.
Another purpose is to create a portal for the tennants to pat for the rent and the services

.Motivation
The landlord asked for a system that helps him to keep track of everything he think it's important for the administration of his rental objects. He asked for this project because right now he is working with Excel sheets and he is keeping every information updated "manually". This project aims to shift this manual work to an automated system.

.Brainstorming process 

=== Quality Goals

[options="header",cols="1,2,2"]
|===
|Nr.|Quality|Motivation
| 1 | _insert_quality_goal_here_ | _insert_motivation_here_
| 2 | _insert_quality_goal_here_ | _insert_motivation_here_
| 3 | _insert_quality_goal_here_ | _insert_motivation_here_
| 4 | _insert_quality_goal_here_ | _insert_motivation_here_
| 5 | _insert_quality_goal_here_ | _insert_motivation_here_
|===

=== Stakeholders

[options="header",cols="1,1,2"]
|===
|Role/Name|Contact|Expectations
| _Customer_ | _<Landlord>_ | _1. What is your business? What are you doing? +
                                Answer: landlord/house owner +
                                2. What challenges you want to solve throughout the project? +
                                Answer: Automation of the processes, integrate billing system, management
                                of the sensor system, ... +
                                3. Are there any existing systems that need to be integrated? +
                                Answer: excel sheets (not sure)+
                                4. What is your product and for whom is it? Who is your target audience? +
                                Answer: the product is mainly for him, no need to generalize to a wider target +
                                5. Is it important for you what technologies are going to be used by us? +
                                Answer: Didn't seem that he cared about the technologies+
                                6. What are the project risks for your company? +
                                Answer: He hasn't said anything about it +
                                7. What are the deadlines? Till what time what should be ready? +
                                Answer: He hasn't said anything about it +
                                8. If it is a REST app do your have the REST endpoints or should we develop them on your side? +
                                Answer: He hasn't said anything about it +
                                9. What is the projects budget? +
                                Answer: He hasn't said anything about it +
                                10. How many people are there in the project and how many you need? +
                                Answer: He hasn't said anything about it +
                                11. Are there any software architecture constraints that we should know about (architectural pattern or design pattern)? +
                                Answer: He hasn't said anything about it +
                                12. Ask about that: the building block view shows the static decomposition of the system into building blocks (modules,
                                components, subsystems, classes, interfaces, packages, libraries, frameworks, layers, partitions, tiers, functions,
                                macros, operations, data structures, ...) as well as their dependencies (relationships, associations, ...) +
                                Answer: He hasn't said anything about it +
                                13. Make sure that we know:
                                * important use cases or features: how do building blocks execute them?
                                * interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
                                * operation and administration: launch, start-up, stop
                                * error and exception scenarios +
                                Answer: He hasn't said anything about it +
                                14. What is your technical infrastructure used to execute your system, with infrastructure elements like geographical
                                locations, environments, computers, processors, channels and net topologies as well as other infrastructure elements and
                                mapping of (software) building blocks to that infrastructure elements. +
                                Answer: He hasn't said anything about it +
                                15. Do you have production/test systems, should we build them? +
                                Answer: He hasn't said anything about it
|===
